[package]
name = "ra4-examples"
version = "0.2.4-dev"
description = "HAL examples for the Renesas RA4 family of MCUs."
license = "GPL-3.0-or-later"
publish = false
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true

[[bin]]
name = "rtc"
required-features = [ "_enable-rtc-beware-of-dragons" ]

[dependencies]
## Core dependencies
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true, optional = true }
defmt-rtt = { version = "1.0.0", optional = true }
panic-probe = { version = "1.0.0" }
critical-section = { workspace = true }

## Embassy dependencies
# embassy-embedded-hal = { version = "0.5.0", default-features = false }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
# embassy-futures = { version = "0.1.2" }
embedded-hal-1 = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }

## Board stuff
ra4-hal = { path = "../ra4-hal", version = "0.2.4-dev", features = [ "unstable-pac" ] }
uno-r4wifi-bsc = { path = "../uno-r4wifi-bsc" }

## Third party stuff
atomic_float = { version = "1.1.0", default-features = false }
heapless = { version = "0.9.2" }
micromath = "2.1"
usb-device = "0.3.2"
usbd-serial = "0.2.2"
# For a signal generator micromath isn't precise enough but libm adds +10K
libm = "0.2.16"

## For the I2C and SPI examples.
mini-sensors = { git = "https://git.sr.ht/~az1/mini-sensors" }

[build-dependencies]
vergen-gitcl = { version = "9" }

[features]
default = [ "defmt", "strict-assert", "uno-r4-wifi" ]
defmt = [
  "dep:defmt",
  "dep:defmt-rtt",
  "panic-probe/print-defmt",
  "embassy-executor/defmt",
  "embassy-time/defmt",
  "embassy-time/defmt-timestamp-uptime",
  "ra4-hal/defmt",
  "uno-r4wifi-bsc/defmt",
  "mini-sensors/defmt"
]
strict-assert = [ "ra4-hal/strict-assert" ]
uno-r4-minima = [ ]
uno-r4-wifi = [ ]
